### ISSUE TITLE
"main" missing from published package.json

### ISSUE THREAD

**Issue by eXigentCoder** [derkoe/remix-azure-functions#6]
Just a heads up, the latest published npm package is missing the "main" entry in the package.json so had to change the require to be `require('@derkoe/remix-azure-functions/dist')` for now, I see it has been fixed in the code though, probably just needs a publish.

**Comment by derkoe** [comment]
This should be fixed now - see https://github.com/derkoe/remix-azure-functions-demo/blob/main/azure/function/index.js for example usage
